### ISSUE TITLE
可以提供更详细的使用文档么

### ISSUE THREAD

**Issue by jiandanliuxing** [SwingCosmic/AssetStudioExporter#1]
这个项目看起来很强的样子，但我下载代码看了下，这似乎并不是一个 exe，更像是一个 dll，可以提供下如何调用的示例代码么？另外这个项目支持 unity2022 的资源解析么？

**Comment by SwingCosmic** [comment]
文档已补充，支持的Unity版本取决于AssetsTools.NET目前支持的版本
